# Generated by Django 3.1.3 on 2020-12-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kierowca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('telefon', models.IntegerField()),
                ('adres', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_zamowienia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_realizacji', models.DateField()),
                ('kierowca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria_app.kierowca')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria_app.klient')),
                ('kucharz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria_app.kucharz')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria_app.pizza')),
            ],
        ),
    ]
